baseURL: "https://ombretta.github.io" 
title: Ombretta Strafforello
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a postdoctoral researcher at KU Leuven, Belgium. My research explores how to model human aesthetic perception with computer vision."
    author: Ombretta Strafforello
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ombretta Strafforello
          subtitle: "I am a computer vision scientist. I currently work as a postdoctoral researcher in Prof. Johan Wagemans' group at KU Leuven (BE), where I explore how computer vision can be used to model human aesthetic perception of natural and artistic images.
            My work focuses on adapting and extending state-of-the-art models, such as vision transformers and large vision-language models, to predict aesthetic appreciation. Additionally, I am exploring how theories from visual perception, particularly regarding the impact of color, symmetry, grouping, and composition, can be integrated into these models.
            Previously, I was a PhD candidate in deep learning for long-term video understanding in Jan van Gemert's Computer Vision lab at TU Delft (NL), in collaboration with the Netherlands Organisation for Applied Scientific Research (TNO)."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ombretta Strafforello
          buttons:
            - name: Papers
              url: papers/
#            - name: Courses
#              url: courses/
#            - name: Data
#              url: data/
#            - name: Books
#              url: books/
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
#            - name: Blog
#              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ombretta.st@gmail.com
#        - name: Zoom
#          url: https://www.zoom.us/my/igelfeld
#        - name: Location
#          url: location/
#        - name: Office Hours
#          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=o2Xe22kAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ombretta
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: YouTube
#          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://x.com/ombrettast

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ombretta Strafforello"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
